# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: signaling-server-service
spec:
  type: LoadBalancer
  selector:
    app: signaling-server # 這個 selector 必須與 Deployment 的 labels 匹配
  ports:
  - protocol: TCP
    port: 80 # 公開 IP 要監聽的埠號
    targetPort: 8080 # 流量要轉發到容器的哪個埠號